# Generated by Django 4.2.4 on 2023-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
